# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(help_text='要发布的应用名称', max_length=200, verbose_name='应用名称')),
                ('team_name', models.CharField(help_text='负责应用的团队名称', max_length=200, verbose_name='团队名称')),
                ('responsible_username', models.CharField(help_text='应用的负责人', max_length=200, verbose_name='负责人名称')),
                ('application_username', models.CharField(help_text='申请人的名称', max_length=200, verbose_name='申请人名称')),
                ('application_description', models.CharField(help_text='关于应用的描述', max_length=200, verbose_name='应用描述')),
                ('deploy_note', models.CharField(help_text='此次发布的步骤说明', max_length=200, verbose_name='发布说明')),
                ('field_name', models.CharField(help_text='help_text', max_length=200, verbose_name='verbose_name')),
                ('os_type', models.CharField(choices=[('windows', 'Windows Server'), ('linux', 'Linux 64')], help_text='应用部署的操作系统', max_length=100, verbose_name='操作系统')),
                ('instance_count', models.IntegerField(help_text='申请应用部署的实例数量', verbose_name='应用部署的实例数')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='更新时间')),
            ],
        ),
    ]
