# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releaserecorder', '0002_auto_20161014_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseapplication',
            name='version',
            field=models.CharField(blank=True, help_text='要发布的应用版本', max_length=200, verbose_name='应用版本'),
        ),
    ]
